# Generated by Django 5.0.6 on 2024-07-01 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_initial_data(apps, schema_editor):
    FishSpecies = apps.get_model('api', 'FishSpecies')
    Bait = apps.get_model('api', 'Bait')

    FishSpecies.objects.create(name="Gädda", latin_name="Esox lucius", description="<p>Gädda är en rovfisk som trivs i sötvatten.</p>")
    FishSpecies.objects.create(name="Gös", latin_name="Sander lucioperca", description="<p>Gös är en uppskattad matfisk.</p>")
    FishSpecies.objects.create(name="Abborre", latin_name="Perca fluviatilis", description="<p>Abborre är en populär sportfisk.</p>")
    FishSpecies.objects.create(name="Lake", latin_name="Lota lota", description="<p>Lake är den enda sötvattenslevande torskfisken.</p>")
    FishSpecies.objects.create(name="Ej bestämd", latin_name="Ej bestämd", description="<p>Ej artbestämd</p>")

    Bait.objects.create(type="Jigg")
    Bait.objects.create(type="Wobbler")
    Bait.objects.create(type="Spinnare")
    Bait.objects.create(type="Skeddrag")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Baits',
            },
        ),
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fish Species',
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_image_url', models.CharField(max_length=255)),
                ('thumbnail_image_url', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('weather', models.CharField(blank=True, max_length=255, null=True)),
                ('weather_icon_url', models.CharField(blank=True, max_length=255, null=True)),
                ('air_temperature', models.FloatField(blank=True, null=True)),
                ('air_pressure', models.IntegerField(blank=True, null=True)),
                ('air_humidity', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_dir', models.CharField(blank=True, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('moon_phase', models.CharField(blank=True, null=True)),
                ('moon_illumination', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('bait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bait')),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fishspecies')),
            ],
            options={
                'verbose_name_plural': 'Fishes',
            },
        ),
        migrations.RunPython(create_initial_data),
    ]
