FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && \
    apt-get install -y libpq-dev gcc && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

COPY wait-for-it.sh .

CMD ["sh", "-c", "./wait-for-it.sh db:5432 -- python manage.py migrate && \
                 python manage.py collectstatic --noinput && \
                 python manage.py createsuperuser --noinput --username ${DJANGO_SUPERUSER_USERNAME} --email ${DJANGO_SUPERUSER_EMAIL} || true && \
                 daphne -b 0.0.0.0 -p 8000 core.asgi:application"]
