# backend/Dockerfile-postgres

FROM postgres:16

RUN apt-get update && \
    apt-get install -y locales && \
    sed -i '/sv_SE.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen sv_SE.UTF-8

ENV LANG sv_SE.UTF-8
ENV LANGUAGE sv_SE:sv
ENV LC_ALL sv_SE.UTF-8